"""Create menu tables

Revision ID: f5ac5e2dd041
Revises: 
Create Date: 2023-12-10 11:48:41.562614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5ac5e2dd041"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "main_menu_items",
        sa.Column("main_menu_item", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_main_menu_items_main_menu_item"),
        "main_menu_items",
        ["main_menu_item"],
        unique=True,
    )
    op.create_table(
        "submenu_items",
        sa.Column("submenu_item", sa.String(length=50), nullable=False),
        sa.Column("main_menu_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["main_menu_id"], ["main_menu_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_submenu_items_submenu_item"),
        "submenu_items",
        ["submenu_item"],
        unique=True,
    )
    op.create_table(
        "dish_recipes",
        sa.Column("dish", sa.String(length=50), nullable=False),
        sa.Column("dish_recipe", sa.Text(), nullable=True),
        sa.Column("submenu_items_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["submenu_items_id"], ["submenu_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dish_recipes_dish"), "dish_recipes", ["dish"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dish_recipes_dish"), table_name="dish_recipes")
    op.drop_table("dish_recipes")
    op.drop_index(op.f("ix_submenu_items_submenu_item"), table_name="submenu_items")
    op.drop_table("submenu_items")
    op.drop_index(
        op.f("ix_main_menu_items_main_menu_item"), table_name="main_menu_items"
    )
    op.drop_table("main_menu_items")
    # ### end Alembic commands ###
